### ISSUE TITLE
生活鯖に/menuがない件

### ISSUE THREAD

**Issue by kinoko2k** [seichi915Network/seichi915ServerCore#10]
生活鯖で/menuが打てなくて、整地鯖に行けない(hub鯖はどうでもはよくないけど)

**Comment by stouma915** [comment]
生活 -> Hub -> 整地を想定しているんですが...
あと各場所違う気がします

**Comment by kinoko2k** [comment]
lifeに置こうと思ったけど、servercoreにしまってるんじゃないの？

**Comment by kinoko2k** [comment]
生活鯖がspawnになるの？

**Comment by stouma915** [comment]
> servercoreにしまってるんじゃないの？
しまっているって何をですか
> 生活鯖がspawnになるの？
????

**Comment by kinoko2k** [comment]
生活=>hub=>整地を想定がわからん

**Comment by stouma915** [comment]
どういう意図ですか
生活から直接整地に行くという意味で返信しましたが

**Comment by kinoko2k** [comment]
生活から整地に行くならば、/menuが開けないのは問題では？

**Comment by stouma915** [comment]
生活から`/hub`と打って、Hubから整地鯖にいけばいいのではないでしょうか

**Comment by kinoko2k** [comment]
生活=>hub=>整地よりも
生活=>整地の方が効率がいい気が(?)

**Comment by stouma915** [comment]
そもそもHubってそういうためのものなんですが...
全鯖に鯖間移動用の`/menu`を生やすのはその鯖の独自機能に干渉する恐れがあるのでHubからの移動はどちらかというとやむを得ないというかなんというか

**Comment by kinoko2k** [comment]
hubは、spawnする場所では？
hubからもいろいろなサーバーが行けるゲートなどがあって、鯖にも、別鯖に行くコマンドがあった方が便利だと思いますよ

**Comment by stouma915** [comment]
> hubは、spawnする場所では？

Hubは中心地などという意味があるので、seichi915では中心地という意味でHub鯖を用意しています
> hubからもいろいろなサーバーが行けるゲートなどがあって、鯖にも、別鯖に行くコマンドがあった方が便利だと思いますよ

ログイン・サーバー移動時にひと手間かかるのと、鯖の独自機能が失われるの、どちらが重要ですか？

**Comment by kinoko2k** [comment]
fm

**Comment by stouma915** [comment]
仮に独自に`/server`というサーバーの一覧を表示するコマンドを各鯖にはやしたとしても、
鯖を増やしたとき、運営方針上、鯖がどんどん増えるseichi915で各鯖に対して変更を適用するのは現実的ではないと思います

**Comment by stouma915** [comment]
必要であれば[seichi915LifeCore](https://github.com/seichi915Network/seichi915LifeCore)に記入してください
